function dq=System(t,q)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Implementation of the fourth-order system [th'', x'''',pth1'']
%INPUT:
%t...time variable
%q...vector of variables of the system, 8 by 1,
%    q=[x;x';x'';x''';th;th';pth1;pth1']
%OUTPUT:
%dq..vector of the solution of the system, 8 by 1
%    dq=[x';x'';x''';x'''';th';th'';pth1';pth1'']
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global M m g l xp0 yp0 eps c n k

%Keplerian potential (eps=0 to disable):
dVepsdx=@(q)-(eps*(4*q(1) - 4*xp0 + 4*l*sin(q(5))))/(2*(q(1) ...
    - xp0 + l*sin(q(5)))^2 + 2*(yp0 - l*cos(q(5)))^2)^2;
dVepsdth=@(q)-(eps*(4*l*cos(q(5))*(q(1) - xp0 + l*sin(q(5))) ...
    + 4*l*sin(q(5))*(yp0 - l*cos(q(5)))))/(2*(q(1) - xp0 + ...
    l*sin(q(5)))^2 + 2*(yp0 - l*cos(q(5)))^2)^2;

%Mollifier potential (c=0 to disable):
%dxdMol2D=@(q) (-(c*eps^4*exp(eps^2/((q(1) - xp0 + ...
%    l*sin(q(5)))^2 - k^2 + (yp0 - l*cos(q(5)))^2))*(2*q(1) - ...
%    2*xp0 + 2*l*sin(q(5))))/((q(1) - xp0 + l*sin(q(5)))^2 - ...
%    k^2 + (yp0 - ...
%    l*cos(q(5)))^2)^2).*(sqrt(abs(q(1)+l*sin(q(5))-xp0).^2+...
%    abs(l*cos(q(5))-yp0).^2)<k);
%dthdMol2D=@(q) (-(c*eps^4*exp(eps^2/((q(1) - xp0 + ...
%    l*sin(q(5)))^2 - k^2 + (yp0 - ...
%    l*cos(q(5)))^2))*(2*l*cos(q(5))*(q(1) - xp0 + ...
%    l*sin(q(5))) + 2*l*sin(q(5))*(yp0 - l*cos(q(5)))))/((q(1) ...
%    - xp0 + l*sin(q(5)))^2 - k^2 + (yp0 - ...
%    l*cos(q(5)))^2)^2).*(sqrt(abs(q(1)+l*sin(q(5))-xp0).^2+...
%    abs(l*cos(q(5))-yp0).^2)<k);

%Vn potential (n=0 to disable):
%dxdVn=@(q)(-n*(2*q(1) - 2*xp0 + ...
%    2*l*sin(q(5)))).*(sqrt((q(1)+l*sin(q(5))-xp0).^2+...
%    (l*cos(q(5))-yp0).^2)<k);
%dthdVn=@(q)(-n*(2*l*cos(q(5))*(q(1) - xp0 + l*sin(q(5))) + ...
%    2*l*sin(q(5))*(yp0 - ...
%    l*cos(q(5))))).*(sqrt((q(1)+l*sin(q(5))-xp0).^2+...
%    (l*cos(q(5))-yp0).^2)<k);

% =========================================================
% SCEGLI QUI IL POTENZIALE cambiando i nomi delle derivate:
%   Kepleriano  -> dVepsdx,  dVepsdth
%   Mollifier   -> dxdMol2D, dthdMol2D
%   Vn          -> dxdVn,    dthdVn
% =========================================================
dVdx  = dVepsdx;    % <-- cambia qui
dVdth = dVepsdth;   % <-- cambia qui

dq = [q(2);...%x'
      q(3);...%x''
      q(4);...%x'''
      (1/(M+m*sin(q(5))^2)^2)*(-dVdx(q)+(2*sin(q(5))*q(8)*q(6))...
      /l+(cos(q(5))*q(7)*q(6)^2)/l-(cos(q(5))*(-dVdth(q)+...
      q(7)*(g*cos(q(5))+sin(q(5))*q(3))/l-2*l*m*cos(q(5))*q(6)^2*...
      (-l*m*sin(q(5))*q(6)^2+(m+M)*q(3)+m*cos(q(5))*(g*sin(q(5))-...
      cos(q(5))*q(3)))-(-l*m*sin(q(5))*q(6)^2+(m+M)*q(3)+m*...
      cos(q(5))*(g*sin(q(5))- cos(q(5))*q(3)))*(-l*m*cos(q(5))*...
      q(6)^2-m*sin(q(5))*(g*sin(q(5))-cos(q(5))*q(3))+m*cos(q(5))*...
      (g*cos(q(5))+sin(q(5))*q(3)))-2*l*m*sin(q(5))*...
      (-l*m*sin(q(5))*q(6)^2+(M+m)*q(3)+m*cos(q(5))*(g*sin(q(5))-...
      cos(q(5))*q(3))*((g*sin(q(5))-cos(q(5))*q(3))/l))-...
      2*m*l*sin(q(5))*q(6)*(-l*m*cos(q(5))*q(6)^3-m*sin(q(5))*...
      q(6)*(g*sin(q(5))-cos(q(5))*q(3))-2*l*m*sin(q(5))*q(6)*...
      ((g*sin(q(5))-cos(q(5))*q(3))/l)+(M+m)*q(4)+m*cos(q(5))*...
      (g*cos(q(5))*q(6)+sin(q(5))*q(6)*q(3)-cos(q(5))*q(4)))))/l...
      +2*m*cos(q(5))*(M+m*sin(q(5))^2)*(q(6)^2)*(g*sin(q(5))-...
      cos(q(5))*q(3))+4^(m^2)*cos(q(5))*(sin(q(5))^2)*(q(6)^2)*...
      (g*sin(q(5))-cos(q(5))*q(3))+(q(7)*sin(q(5))*((g*sin(q(5))-...
      cos(q(5))*q(3))/l))/l+2*m*(M+m*sin(q(5))^2)*sin(q(5))*(g*...
      sin(q(5))-cos(q(5))*q(3))*((g*sin(q(5))-cos(q(5))*q(3))/l)...
      -(2*m*cos(q(5))*sin(q(5))*(-l*m*sin(q(5))*q(6)^2+...
      (m+M)*q(3)+m*cos(q(5))*(g*sin(q(5))-cos(q(5))*q(3)))+(M+...
      m*sin(q(5))^2)*(-l*m*cos(q(5))*q(6)^2-m*sin(q(5))*(g*...
      sin(q(5))-cos(q(5))*q(3))+ m*cos(q(5))*(g*cos(q(5))+...
      sin(q(5))*q(3))))*((g*sin(q(5))-cos(q(5))*q(3))/l)-q(4)*(M+...
      m*sin(q(5))^2)^2+2*m*(M+m*sin(q(5))^2)*sin(q(5))*q(6)*(g*...
      cos(q(5))*q(6)+sin(q(5))*q(6)*q(3)-cos(q(5))*q(4))-q(6)*...
      (2*m*q(6)*(cos(q(5))^2)*(-l*m*sin(q(5))*q(6)^2+(M+m)*q(3)...
      +m*cos(q(5))*(g*sin(q(5))-cos(q(5))*q(3)))-2*m*q(6)*...
      (sin(q(5))^2)*(-l*m*sin(q(5))*q(6)^2+(M+m)*q(3)+m*...
      cos(q(5))*(g*sin(q(5))-cos(q(5))*q(3)))+2*m*cos(q(5))*...
      sin(q(5))*q(6)*(-l*m*cos(q(5))*q(6)^2- m*sin(q(5))*(g*...
      sin(q(5))-q(3)*cos(q(5)))+m*cos(q(5))*(g*cos(q(5))+...
      sin(q(5))*q(3)))+2*m*cos(q(5))*sin(q(5))*(-l*m*cos(q(5))*...
      q(6)^3- m*sin(q(5))*q(6)*(g*sin(q(5))-q(3)*cos(q(5)))-...
      2*l*m*sin(q(5))*q(6)*((g*sin(q(5))-cos(q(5))*q(3))/l)+(M+...
      m)*q(4)+m*cos(q(5))*(g*cos(q(5))*q(6)+sin(q(5))*q(6)*((g*...
      sin(q(5))-cos(q(5))*q(3))/l)-cos(q(5))*q(4)))+(M+m*...
      sin(q(5))^2)*(l*m*sin(q(5))*q(6)^3-m*cos(q(5))*q(6)*(g*...
      sin(q(5))-q(3)*cos(q(5)))-m*sin(q(5))*q(6)*(g*sin(q(5))+...
      q(3)*cos(q(5)))-2*l*m*cos(q(5))*q(6)*((g*sin(q(5))-...
      cos(q(5))*q(3))/l)-m*sin(q(5))*(g*cos(q(5))*q(6)+...
      sin(q(5))*q(6)*q(3)-cos(q(5))*q(4))+m*cos(q(5))*...
      (-g*sin(q(5))*q(6)+cos(q(5))*q(6)*q(3)+sin(q(5))*q(4)))));...
      %equation for x''''
      q(6);...%theta'
      (g*sin(q(5))-cos(q(5))*q(3))/l;...%equation for theta''
      q(8);...%pth1'
      -dVdth(q)+q(7)*(g*cos(q(5))+sin(q(5))*q(3))/l-2*l*m*...
      cos(q(5))*q(6)^2*(-l*m*sin(q(5))*q(6)^2+(m+M)*q(3)+m*...
      cos(q(5))*(g*sin(q(5))-cos(q(5))*q(3)))-(-l*m*sin(q(5))*...
      q(6)^2+(m+M)*q(3)+m*cos(q(5))*(g*sin(q(5))-cos(q(5))*...
      q(3)))*(-l*m*cos(q(5))*q(6)^2-m*sin(q(5))*(g*sin(q(5))-...
      cos(q(5))*q(3))+m*cos(q(5))*(g*cos(q(5))+sin(q(5))*q(3)))-...
      2*l*m*sin(q(5))*(-l*m*sin(q(5))*q(6)^2+(M+m)*q(3)+m*...
      cos(q(5))*(g*sin(q(5))-cos(q(5))*q(3))*((g*sin(q(5))-...
      cos(q(5))*q(3))/l))-2*m*l*sin(q(5))*q(6)*(-l*m*cos(q(5))*...
      q(6)^3-m*sin(q(5))*q(6)*(g*sin(q(5))-cos(q(5))*q(3))-...
      2*l*m*sin(q(5))*q(6)*((g*sin(q(5))-cos(q(5))*q(3))/l)+...
      (M+m)*q(4)+m*cos(q(5))*(g*cos(q(5))*q(6)+sin(q(5))*q(6)*...
      q(3)-cos(q(5))*q(4)))];%last equation is for pth1''
end